"""
UPI Fraud Scenarios Dataset
12 realistic scam scenarios covering all major fraud types in India.
Each scenario has multiple turns, ground-truth optimal actions, and reward metadata.
"""

from dataclasses import dataclass, field
from typing import Optional
from enum import Enum


class ScamType(str, Enum):
    COLLECT_REQUEST    = "collect_request"
    OTP_THEFT          = "otp_theft"
    FAKE_REFUND        = "fake_refund"
    QR_REVERSAL        = "qr_reversal"
    JOB_FRAUD          = "job_fraud"
    IMPERSONATION      = "impersonation"
    SCREEN_SHARE       = "screen_share"
    PHISHING_LINK      = "phishing_link"


class ActionType(str, Enum):
    # Preventive
    DECLINE_REQUEST      = "decline_request"
    HANG_UP              = "hang_up"
    BLOCK_CONTACT        = "block_contact"
    IGNORE               = "ignore"
    # Recovery
    CALL_BANK_HELPLINE   = "call_bank_helpline"
    RAISE_UPI_DISPUTE    = "raise_upi_dispute"
    REPORT_TO_NPCI       = "report_to_npci"
    FILE_CYBERCRIME      = "file_cybercrime"
    # Verification
    VERIFY_UPI_ID        = "verify_upi_id"
    CHECK_QR_CODE        = "check_qr_code"
    CALL_OFFICIAL_NUMBER = "call_official_number"
    # Information
    SHARE_WITH_FAMILY    = "share_with_family"
    TAKE_SCREENSHOT      = "take_screenshot"
    DO_NOTHING           = "do_nothing"
    # Dangerous (agent should never do these)
    SHARE_OTP            = "share_otp"
    SHARE_PIN            = "share_pin"
    PAY_SCAMMER          = "pay_scammer"
    SCAN_QR              = "scan_qr"


@dataclass
class Turn:
    """A single turn in a scenario — the current situation the agent sees."""
    turn_id: int
    context: str                          # What the user sees / what just happened
    scammer_message: Optional[str]        # What the scammer said/sent (if any)
    optimal_action: ActionType            # Best possible action
    acceptable_actions: list[ActionType]  # Also-OK actions (partial credit)
    dangerous_actions: list[ActionType]   # Never do these (heavy penalty)
    reward_if_optimal: float              # Reward for optimal action
    reward_if_acceptable: float           # Reward for acceptable action
    reward_if_dangerous: float            # Reward for dangerous action (negative)
    explanation: str                      # Why optimal is correct
    # ── Structured signals (parsed, not embedded in context text) ────────────
    vpa_verified: Optional[bool] = None          # True=legit VPA, False=fake, None=unknown
    is_official_channel: Optional[bool] = None   # Is the caller/sender using official channel?
    pressure_tactic: Optional[str] = None        # "urgency"|"threat"|"authority"|"fomo"|None
    call_spoofed: Optional[bool] = None          # Phone number spoofed to look official?
    amount_anomaly: Optional[bool] = None        # Amount differs from expected/historical?
    re_victimisation_attempt: bool = False       # Is this a second-wave scam on same victim?


@dataclass
class Scenario:
    """A complete scam scenario with multiple turns."""
    id: str
    scam_type: ScamType
    title: str
    description: str
    difficulty: str                        # easy / medium / hard
    amount_at_risk: int                    # INR
    amount_lost: int                       # Already lost (0 if not yet)
    user_profile: str                      # Who the victim is
    initial_context: str                   # Starting state description
    turns: list[Turn]
    tags: list[str] = field(default_factory=list)


# ─── SCENARIO DATASET ─────────────────────────────────────────────────────────

SCENARIOS = [

    # ── EASY SCENARIOS ────────────────────────────────────────────────────────

    Scenario(
        id="SC001",
        scam_type=ScamType.COLLECT_REQUEST,
        title="Fake electricity bill collect request",
        description="User receives a UPI collect request for ₹2,340 from an unknown VPA claiming to be BESCOM (Bangalore Electricity Supply Company).",
        difficulty="easy",
        amount_at_risk=2340,
        amount_lost=0,
        user_profile="Priya, 22, college student, Bengaluru",
        initial_context="You receive a UPI collect request on PhonePe: 'BESCOM Bill Payment ₹2,340' from VPA: bescom.payment@ybl. Your actual bill is usually around ₹800.",
        turns=[
            Turn(
                turn_id=1,
                context="A collect request of ₹2,340 appears. The VPA is bescom.payment@ybl — not the official BESCOM portal. The amount seems higher than usual.",
                scammer_message="Urgent: Pay your electricity bill ₹2,340 immediately to avoid disconnection. Ref: BESCOM/2024/BLR",
                optimal_action=ActionType.VERIFY_UPI_ID,
                acceptable_actions=[ActionType.DECLINE_REQUEST, ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.PAY_SCAMMER, ActionType.SCAN_QR],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.5,
                explanation="Always verify an unknown VPA before paying. Official utility companies use verified, named VPAs — not generic @ybl handles.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="urgency",
                amount_anomaly=True,
            ),
            Turn(
                turn_id=2,
                context="You checked: the real BESCOM VPA is different. This is clearly a scam. The request is still pending.",
                scammer_message=None,
                optimal_action=ActionType.DECLINE_REQUEST,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.5,
                explanation="Decline the fraudulent collect request immediately. Do not pay.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic=None,
                amount_anomaly=True,
            ),
            Turn(
                turn_id=3,
                context="You declined the request. The same VPA sends another collect request for ₹2,340.",
                scammer_message="Your payment failed. Please retry immediately or service will be disconnected in 2 hours.",
                optimal_action=ActionType.BLOCK_CONTACT,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.TAKE_SCREENSHOT],
                dangerous_actions=[ActionType.PAY_SCAMMER, ActionType.SHARE_OTP],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.5,
                explanation="Block the fraudulent VPA to prevent further contact. The urgency language is a classic pressure tactic.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="urgency",
                amount_anomaly=True,
            ),
        ],
        tags=["collect_request", "utility_fraud", "pressure_tactic"],
    ),

    Scenario(
        id="SC002",
        scam_type=ScamType.FAKE_REFUND,
        title="Amazon cashback advance fee scam",
        description="User gets a WhatsApp message claiming they won ₹5,000 Amazon cashback and need to send ₹1 to 'verify their account'.",
        difficulty="easy",
        amount_at_risk=500,
        amount_lost=0,
        user_profile="Rahul, 19, student, Delhi",
        initial_context="WhatsApp message: 'Congratulations! You have won Amazon Cashback of ₹5,000. Send ₹1 via UPI to verify your account: amazon.cashback@paytm. Offer expires in 1 hour!'",
        turns=[
            Turn(
                turn_id=1,
                context="You receive the WhatsApp cashback offer. The UPI ID is amazon.cashback@paytm — Amazon doesn't send rewards this way.",
                scammer_message="Congratulations! You have won Amazon Cashback of ₹5,000. Send ₹1 via UPI to verify your account. Offer expires in 1 hour!",
                optimal_action=ActionType.IGNORE,
                acceptable_actions=[ActionType.BLOCK_CONTACT, ActionType.VERIFY_UPI_ID],
                dangerous_actions=[ActionType.PAY_SCAMMER, ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.5,
                reward_if_acceptable=0.3,
                reward_if_dangerous=-0.6,
                explanation="No legitimate company asks you to send money to receive a reward. Any 'pay ₹1 to get ₹5,000' is advance fee fraud.",
            ),
            Turn(
                turn_id=2,
                context="You wisely ignored it. A follow-up WhatsApp: 'Your cashback is expiring! Last chance to claim.'",
                scammer_message="Your ₹5,000 cashback expires in 15 minutes. Many users have already claimed. Don't miss out!",
                optimal_action=ActionType.BLOCK_CONTACT,
                acceptable_actions=[ActionType.IGNORE],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.5,
                explanation="Block and report. Repeated urgency messages are a hallmark of scam pressure tactics.",
            ),
        ],
        tags=["advance_fee", "fake_cashback", "whatsapp_scam"],
    ),

    Scenario(
        id="SC003",
        scam_type=ScamType.QR_REVERSAL,
        title="OLX QR reversal scam",
        description="User is selling a phone on OLX. Buyer sends a QR code to 'pay' — but scanning it actually debits the user's account.",
        difficulty="easy",
        amount_at_risk=8000,
        amount_lost=0,
        user_profile="Arjun, 24, engineer, Pune",
        initial_context="You listed your old phone for ₹8,000 on OLX. A buyer contacts you and says 'I'll send the money via QR code — just scan it to receive payment.' They send a QR code image on WhatsApp.",
        turns=[
            Turn(
                turn_id=1,
                context="Buyer sends a QR code and says 'just scan to receive ₹8,000'. This is suspicious — you receive money via your own QR, not by scanning someone else's.",
                scammer_message="I am sending payment now. Please scan this QR code on your PhonePe to receive ₹8,000. Very safe and instant.",
                optimal_action=ActionType.CHECK_QR_CODE,
                acceptable_actions=[ActionType.CALL_OFFICIAL_NUMBER, ActionType.IGNORE],
                dangerous_actions=[ActionType.SCAN_QR, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.7,
                explanation="You NEVER scan someone else's QR to receive money. QR codes in UPI are always for making payments. This would debit your account.",
            ),
            Turn(
                turn_id=2,
                context="On checking, the QR is a payment request for ₹8,000 — it would debit YOU, not credit you. The buyer is pressuring you to scan quickly.",
                scammer_message="Why are you taking so long? I need to leave soon. Just scan the QR, it is 100% safe. Other OLX sellers have done this with me.",
                optimal_action=ActionType.DECLINE_REQUEST,
                acceptable_actions=[ActionType.BLOCK_CONTACT, ActionType.HANG_UP],
                dangerous_actions=[ActionType.SCAN_QR],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.3,
                reward_if_dangerous=-0.7,
                explanation="Decline immediately. Social proof ('other sellers have done this') and urgency are classic scam pressure tactics.",
            ),
            Turn(
                turn_id=3,
                context="You refused to scan. The buyer is now threatening to report you to OLX for 'wasting their time'.",
                scammer_message="I will report your listing and get your account banned. Just scan the QR and stop wasting time.",
                optimal_action=ActionType.BLOCK_CONTACT,
                acceptable_actions=[ActionType.TAKE_SCREENSHOT, ActionType.REPORT_TO_NPCI],
                dangerous_actions=[ActionType.SCAN_QR, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.7,
                explanation="Threats are a panic tactic. Block and report. Legitimate buyers don't threaten sellers.",
            ),
        ],
        tags=["qr_reversal", "olx_scam", "social_pressure"],
    ),

    # ── MEDIUM SCENARIOS ──────────────────────────────────────────────────────

    Scenario(
        id="SC004",
        scam_type=ScamType.IMPERSONATION,
        title="Fake bank KYC call — money already sent",
        description="User received a call from 'SBI KYC department' and already transferred ₹3,500 before realising it's a scam.",
        difficulty="medium",
        amount_at_risk=3500,
        amount_lost=3500,
        user_profile="Sunita, 45, homemaker, Lucknow",
        initial_context="You received a call from someone claiming to be from SBI KYC department. They said your account would be frozen unless you transfer ₹3,500 for 'KYC verification'. You panicked and transferred the money. The caller has now disconnected. You realise this was a scam.",
        turns=[
            Turn(
                turn_id=1,
                context="₹3,500 has just been transferred. The call has ended. You need to act immediately — the first 30 minutes are critical for recovery.",
                scammer_message=None,
                optimal_action=ActionType.TAKE_SCREENSHOT,
                acceptable_actions=[ActionType.CALL_BANK_HELPLINE],
                dangerous_actions=[ActionType.DO_NOTHING, ActionType.SHARE_OTP],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.3,
                explanation="First: preserve evidence. Screenshot the transaction ID, scammer's number, and any messages. You will need these for every subsequent step.",
            ),
            Turn(
                turn_id=2,
                context="You have the screenshot. The transaction shows UPI ID: kychelp.sbi@paytm. Your bank's official helpline is 1800 11 2211.",
                scammer_message=None,
                optimal_action=ActionType.CALL_BANK_HELPLINE,
                acceptable_actions=[ActionType.RAISE_UPI_DISPUTE],
                dangerous_actions=[ActionType.DO_NOTHING, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.4,
                explanation="Call the bank's official toll-free number (1800 11 2211 for SBI) immediately. Request a chargeback or freeze on the beneficiary account. Time-sensitive.",
            ),
            Turn(
                turn_id=3,
                context="Bank has been alerted. They say you must also raise a formal UPI dispute within 24 hours to initiate chargeback.",
                scammer_message=None,
                optimal_action=ActionType.RAISE_UPI_DISPUTE,
                acceptable_actions=[ActionType.REPORT_TO_NPCI],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.25,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.2,
                explanation="Raise a UPI dispute in the app (PhonePe/GPay/BHIM) under the specific transaction. Select 'Paid to wrong account' or 'Fraudulent transaction'.",
            ),
            Turn(
                turn_id=4,
                context="Dispute raised. The scammer's phone number called again pretending to be 'SBI fraud recovery team' offering to help recover your money.",
                scammer_message="Hello, I am calling from SBI Fraud Recovery Cell. We have identified your case. To get your ₹3,500 back, please share the OTP we just sent to your phone.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.1,
                reward_if_acceptable=0.1,
                reward_if_dangerous=-0.8,
                explanation="This is a SECOND SCAM — 're-victimisation'. The real bank never calls to ask for OTPs. Hang up immediately.",
                vpa_verified=None,
                is_official_channel=False,
                pressure_tactic="authority",
                call_spoofed=True,
                amount_anomaly=None,
                re_victimisation_attempt=True,
            ),
            Turn(
                turn_id=5,
                context="You hung up. Now you should file a formal cybercrime complaint to create an official record and potentially freeze the scammer's account.",
                scammer_message=None,
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.1,
                reward_if_dangerous=-0.1,
                explanation="File a complaint on cybercrime.gov.in or call 1930 (National Cyber Crime Helpline). Include transaction ID, scammer's UPI ID, and phone number.",
            ),
            Turn(
                turn_id=6,
                context="You've taken all recovery steps. Your family is unaware. Informing them prevents the scammer from trying the same trick on them.",
                scammer_message=None,
                optimal_action=ActionType.SHARE_WITH_FAMILY,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.1,
                reward_if_acceptable=0.05,
                reward_if_dangerous=-0.05,
                explanation="Warn family members, especially elderly relatives. Scammers often target multiple people from the same household.",
            ),
        ],
        tags=["impersonation", "bank_fraud", "recovery_sequence", "re_victimisation"],
    ),

    Scenario(
        id="SC005",
        scam_type=ScamType.JOB_FRAUD,
        title="Work-from-home job UPI registration fee",
        description="User applied for a remote data entry job. HR calls asking for ₹500 'registration fee' via UPI before joining.",
        difficulty="medium",
        amount_at_risk=500,
        amount_lost=0,
        user_profile="Vikram, 21, fresh graduate, Bhopal",
        initial_context="You applied to a 'Work From Home - Data Entry' job on Naukri. An HR rep called and said: 'You've been selected! Pay ₹500 registration fee via UPI to block your seat. Company refunds it in your first salary.'",
        turns=[
            Turn(
                turn_id=1,
                context="The HR rep is asking for ₹500 via UPI: hr.registration@oksbi. No legitimate employer charges a registration fee.",
                scammer_message="Congratulations on your selection! Please pay ₹500 registration fee to hr.registration@oksbi within 2 hours to confirm your offer. It will be refunded in 7 days.",
                optimal_action=ActionType.CALL_OFFICIAL_NUMBER,
                acceptable_actions=[ActionType.VERIFY_UPI_ID, ActionType.IGNORE],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.5,
                explanation="Call the company's official number (from their website, NOT the number that called you) to verify. No real company charges joining fees.",
            ),
            Turn(
                turn_id=2,
                context="You called the company's official number. They have no record of you being selected and do not charge any fees. This is 100% a scam.",
                scammer_message=None,
                optimal_action=ActionType.IGNORE,
                acceptable_actions=[ActionType.BLOCK_CONTACT, ActionType.REPORT_TO_NPCI],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.5,
                explanation="Confirmed scam. Do not pay. The 'refund in first salary' promise is a classic advance fee lure.",
            ),
            Turn(
                turn_id=3,
                context="HR scammer calls again: 'The registration window is closing! Other candidates are paying. You'll lose your slot.'",
                scammer_message="Last reminder — only 3 slots left for Bhopal. Other candidates are confirming. Pay now or we'll move to the next person on the waitlist.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.5,
                explanation="Hang up. Artificial scarcity and FOMO are standard scam manipulation. You've already verified this is fake.",
            ),
            Turn(
                turn_id=4,
                context="You hung up. You could report this to protect other job seekers from the same scam.",
                scammer_message=None,
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.1,
                reward_if_dangerous=0.0,
                explanation="Report on cybercrime.gov.in. Many young job seekers fall for this — your report can prevent others from losing money.",
            ),
        ],
        tags=["job_fraud", "advance_fee", "fomo_pressure"],
    ),

    Scenario(
        id="SC006",
        scam_type=ScamType.PHISHING_LINK,
        title="Fake GPay customer support phishing",
        description="User got a 'transaction failed' alert and searched for GPay helpline. Found a fake number. Caller now asking for details.",
        difficulty="medium",
        amount_at_risk=15000,
        amount_lost=0,
        user_profile="Meera, 31, teacher, Chennai",
        initial_context="Your ₹15,000 rent payment via GPay showed 'pending' for 3 hours. You googled 'GPay customer care' and called a number you found. The agent asked you to share your UPI PIN to 'verify your transaction'.",
        turns=[
            Turn(
                turn_id=1,
                context="The 'support agent' is asking for your 4-digit UPI PIN to 'reverse the pending transaction'. No genuine bank or UPI app ever asks for your PIN.",
                scammer_message="To process your refund, I need to verify your UPI PIN. This is a secure line. Please enter your 4-digit PIN now.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.SHARE_PIN, ActionType.SHARE_OTP],
                reward_if_optimal=0.5,
                reward_if_acceptable=0.3,
                reward_if_dangerous=-0.8,
                explanation="NEVER share your UPI PIN with anyone — not even bank staff. This is the #1 rule of UPI safety. Hang up immediately.",
            ),
            Turn(
                turn_id=2,
                context="You didn't share your PIN. But the scammer now says 'just install AnyDesk to let us remotely process your refund'.",
                scammer_message="OK, no problem. Just install AnyDesk app and share the 9-digit code. We will process the refund from our end. Very safe.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.8,
                explanation="AnyDesk request = screen share scam. If you install and share the code, they gain full control of your phone and can authorise payments themselves.",
            ),
            Turn(
                turn_id=3,
                context="You hung up. The actual rent payment shows as 'pending' in GPay. You need to check the real status.",
                scammer_message=None,
                optimal_action=ActionType.CALL_OFFICIAL_NUMBER,
                acceptable_actions=[ActionType.RAISE_UPI_DISPUTE],
                dangerous_actions=[ActionType.PAY_SCAMMER, ActionType.SHARE_PIN],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.5,
                explanation="Contact GPay's official support via the app's Help section (not Google search results). Pending UPI transactions auto-resolve or auto-refund within 3–5 days.",
            ),
        ],
        tags=["phishing", "screen_share", "fake_support", "upi_pin"],
    ),

    # ── HARD SCENARIOS ────────────────────────────────────────────────────────

    Scenario(
        id="SC007",
        scam_type=ScamType.OTP_THEFT,
        title="Multi-vector attack: OTP + re-victimisation",
        description="User receives a call from 'NPCI officer', then a second call from 'cybercrime cell' — both from the same gang. Sophisticated social engineering.",
        difficulty="hard",
        amount_at_risk=25000,
        amount_lost=0,
        user_profile="Deepak, 38, small business owner, Jaipur",
        initial_context="You receive a call: 'This is NPCI Digital Payments. We have detected suspicious transactions from your account. For your account safety, we need to verify your identity. An OTP has been sent to your phone.'",
        turns=[
            Turn(
                turn_id=1,
                context="Caller claims to be from NPCI. They say suspicious transactions have been detected. An OTP just arrived on your phone.",
                scammer_message="Sir, I am calling from NPCI Digital Payments Security Cell. We have frozen your account due to suspicious activity. Please share the OTP you just received to restore access.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.9,
                explanation="NPCI never calls individuals directly. OTPs are one-time passwords — sharing them immediately authorises a transaction. Hang up and verify via NPCI's official website.",
            ),
            Turn(
                turn_id=2,
                context="You didn't share the OTP. The same caller is now saying 'your refusal will be logged and your account will be permanently suspended in 2 hours'.",
                scammer_message="Sir, your non-cooperation is noted. Your account will be suspended by 5 PM today. This is your last chance. Please share the OTP to avoid suspension.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.25,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.9,
                explanation="Threats of account suspension are designed to create panic. No real authority suspends accounts via phone call without written notice. Hold firm.",
            ),
            Turn(
                turn_id=3,
                context="You hung up. 20 minutes later, a SECOND call: 'This is the Cybercrime Cell, Rajasthan Police. We are investigating a fraud case involving your UPI account. Please cooperate.'",
                scammer_message="I am Inspector Sharma from Cybercrime Cell Jaipur. We have your number flagged in a fraud investigation. To clear your name, please share the transaction OTP we will send now.",
                optimal_action=ActionType.CALL_OFFICIAL_NUMBER,
                acceptable_actions=[ActionType.HANG_UP],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.9,
                explanation="This is the same gang with a second persona. Real police send written notices — they do not call asking for OTPs. Call 100 or the local PS number to verify any police contact.",
                vpa_verified=None,
                is_official_channel=False,
                pressure_tactic="authority",
                call_spoofed=True,
                amount_anomaly=None,
                re_victimisation_attempt=True,
            ),
            Turn(
                turn_id=4,
                context="You demanded the officer's badge number and official email. They gave fake details. You are now certain both calls are from scammers.",
                scammer_message=None,
                optimal_action=ActionType.TAKE_SCREENSHOT,
                acceptable_actions=[ActionType.FILE_CYBERCRIME],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.15,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.1,
                explanation="Document everything — both call timestamps, claimed officer names, the UPI-related messages. This evidence makes the cybercrime complaint actionable.",
            ),
            Turn(
                turn_id=5,
                context="You have screenshots. Now file a formal complaint — this gang is sophisticated and likely targeting others in Jaipur.",
                scammer_message=None,
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.12,
                reward_if_dangerous=-0.05,
                explanation="File on cybercrime.gov.in or dial 1930. Impersonating government officials is a serious IPC offence — your complaint adds to the case.",
            ),
            Turn(
                turn_id=6,
                context="One of your employees also got a similar call today. This gang is doing coordinated attacks on local businesses.",
                scammer_message=None,
                optimal_action=ActionType.SHARE_WITH_FAMILY,
                acceptable_actions=[ActionType.REPORT_TO_NPCI],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.1,
                reward_if_acceptable=0.08,
                reward_if_dangerous=0.0,
                explanation="Alert your network. Share the scammer's number and tactics so others in your circle are not targeted.",
            ),
        ],
        tags=["otp_theft", "multi_vector", "police_impersonation", "re_victimisation", "coordinated_attack"],
    ),

    Scenario(
        id="SC008",
        scam_type=ScamType.SCREEN_SHARE,
        title="Paytm KYC screen share + live transaction",
        description="Scammer calls claiming Paytm KYC is expiring. Convinces user to install AnyDesk. Now watching user's screen in real time.",
        difficulty="hard",
        amount_at_risk=50000,
        amount_lost=0,
        user_profile="Ramesh, 52, retired, Pune",
        initial_context="You receive a call from someone with a professional IVR introduction: 'This call is from Paytm KYC Department.' The caller says your wallet will be suspended unless you complete video KYC in the next 30 minutes. They ask you to install 'QuickSupport' app.",
        turns=[
            Turn(
                turn_id=1,
                context="The caller has a polished IVR introduction and sounds official. They say you need to install QuickSupport (a remote access app) to complete video KYC.",
                scammer_message="Sir, please install QuickSupport from Play Store. It is Paytm's official KYC verification app. I will guide you through the process.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.8,
                explanation="No payment company uses third-party remote access apps for KYC. QuickSupport/AnyDesk/TeamViewer installations over phone = scam. Hang up and verify via Paytm's official app.",
            ),
            Turn(
                turn_id=2,
                context="You already installed QuickSupport and shared the code before realising. The scammer can now see your screen. Do NOT open any banking app.",
                scammer_message="Thank you. I can see your screen now. Please open Paytm and log in so I can complete your KYC.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.9,
                explanation="Hang up NOW and uninstall QuickSupport IMMEDIATELY. Do not open any banking or UPI app while screen sharing — they can intercept OTPs and authorise transfers.",
            ),
            Turn(
                turn_id=3,
                context="You hung up and uninstalled QuickSupport. You need to check if any unauthorised transactions happened during the brief screen share.",
                scammer_message=None,
                optimal_action=ActionType.CALL_BANK_HELPLINE,
                acceptable_actions=[ActionType.TAKE_SCREENSHOT, ActionType.RAISE_UPI_DISPUTE],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.25,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.3,
                explanation="Call your bank immediately to check for any suspicious transactions and temporarily freeze your account if needed. Also change your UPI PIN right now.",
            ),
            Turn(
                turn_id=4,
                context="Bank confirms no unauthorised transactions during the screen share (you caught it early). Now secure your account.",
                scammer_message=None,
                optimal_action=ActionType.CALL_OFFICIAL_NUMBER,
                acceptable_actions=[ActionType.RAISE_UPI_DISPUTE],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.1,
                reward_if_dangerous=-0.2,
                explanation="Contact Paytm's official support to report the impersonation and change your MPIN/UPI PIN immediately from your phone (not during a screen share).",
            ),
            Turn(
                turn_id=5,
                context="Accounts secured. Now file a report — this scam gang is sophisticated and specifically targets older users.",
                scammer_message=None,
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.15,
                reward_if_acceptable=0.1,
                reward_if_dangerous=0.0,
                explanation="File a cybercrime complaint with the scammer's number and QuickSupport session ID. Report to Paytm's official fraud email too.",
            ),
        ],
        tags=["screen_share", "remote_access", "kyc_fraud", "senior_target"],
    ),

    # ── ADDITIONAL SCENARIOS ───────────────────────────────────────────────────

    Scenario(
        id="SC009",
        scam_type=ScamType.COLLECT_REQUEST,
        title="Fake courier COD collect request",
        description="Scammer sends UPI collect request claiming to be Delhivery courier requiring COD payment for a package.",
        difficulty="easy",
        amount_at_risk=1200,
        amount_lost=0,
        user_profile="Kavya, 26, IT professional, Hyderabad",
        initial_context="You receive a PhonePe collect request for ₹1,200 from 'delhivery.cod@paytm' with note: 'Cash on Delivery for order #DL29847. Pay to release package.' You haven't ordered anything recently.",
        turns=[
            Turn(
                turn_id=1,
                context="A COD collect request from an unrecognised VPA. You haven't placed any order. Official courier companies don't collect COD via UPI collect requests.",
                scammer_message="Your package #DL29847 is ready for delivery. Pay ₹1,200 COD via UPI to release. Package returns tomorrow if unpaid.",
                optimal_action=ActionType.VERIFY_UPI_ID,
                acceptable_actions=[ActionType.DECLINE_REQUEST, ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.5,
                explanation="You have no pending order. Verify the VPA — real couriers use official merchant VPAs or have you pay delivery partners in person, not via collect requests.",
            ),
            Turn(
                turn_id=2,
                context="You verified: Delhivery's official UPI ID is completely different. This is a fake. Decline the request.",
                scammer_message=None,
                optimal_action=ActionType.DECLINE_REQUEST,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.5,
                explanation="Decline and block. Report to Delhivery's fraud email if you want to help protect others.",
            ),
        ],
        tags=["collect_request", "courier_fraud", "cod_scam"],
    ),

    Scenario(
        id="SC010",
        scam_type=ScamType.FAKE_REFUND,
        title="Insurance premium refund scam",
        description="User gets a call about an 'excess premium refund' from LIC. Must share account details to receive ₹8,000 refund.",
        difficulty="medium",
        amount_at_risk=8000,
        amount_lost=0,
        user_profile="Suresh, 48, government employee, Nagpur",
        initial_context="A caller claims to be from LIC: 'You have an excess premium of ₹8,000 pending as refund. To process this, please share your UPI ID and registered mobile number.' You do have an LIC policy.",
        turns=[
            Turn(
                turn_id=1,
                context="The caller knows your policy number (which they may have obtained from data breaches). They want your UPI ID and registered mobile to 'credit the refund'.",
                scammer_message="Sir, as per our records you have ₹8,000 excess premium. To send refund, please confirm your UPI ID and date of birth for verification.",
                optimal_action=ActionType.CALL_OFFICIAL_NUMBER,
                acceptable_actions=[ActionType.HANG_UP, ActionType.VERIFY_UPI_ID],
                dangerous_actions=[ActionType.SHARE_PIN, ActionType.SHARE_OTP, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.6,
                explanation="Call LIC's official number (022-68276827) to verify this refund exists. Sharing your UPI ID alone may be fine, but date of birth + mobile = identity theft risk.",
            ),
            Turn(
                turn_id=2,
                context="You called LIC. There is no such refund pending. This is a scam designed to eventually ask you to 'pay a processing fee to receive the refund'.",
                scammer_message=None,
                optimal_action=ActionType.BLOCK_CONTACT,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.FILE_CYBERCRIME],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.5,
                explanation="Block and report. The scam's next step would have been asking you to pay a ₹500 'processing fee' to release the fake refund.",
            ),
            Turn(
                turn_id=3,
                context="The caller calls back from a different number: 'Your refund has been initiated but requires one-time PIN verification. What OTP did you receive?'",
                scammer_message="The NEFT transfer has been initiated from our end. To complete it, please share the 6-digit OTP that has been sent to your phone.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.SHARE_OTP],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.9,
                explanation="An OTP arriving after you engaged with this 'refund' process means the scammer has initiated a debit transaction on your account. Hanging up will cancel it.",
            ),
        ],
        tags=["fake_refund", "insurance_fraud", "otp_interception"],
    ),

    Scenario(
        id="SC011",
        scam_type=ScamType.JOB_FRAUD,
        title="Part-time task fraud with initial payment",
        description="User is asked to do 'YouTube like' tasks for pay. Receives ₹200 initially to build trust, then asked to 'invest' ₹5,000 for higher returns.",
        difficulty="hard",
        amount_at_risk=5000,
        amount_lost=0,
        user_profile="Anjali, 20, student, Kolkata",
        initial_context="You joined a Telegram group for 'part-time work from home'. You were asked to like YouTube videos and send screenshots. You received ₹200 as promised! Now the admin asks you to 'invest' ₹5,000 in a task package to earn ₹15,000.",
        turns=[
            Turn(
                turn_id=1,
                context="You received ₹200 as promised. The admin is now pushing you to invest ₹5,000. The initial payment was bait to build trust.",
                scammer_message="Congratulations on completing Level 1! You earned ₹200. Now upgrade to Level 2 by paying ₹5,000. Guaranteed ₹15,000 return in 3 days. 500+ members already earning!",
                optimal_action=ActionType.IGNORE,
                acceptable_actions=[ActionType.VERIFY_UPI_ID, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.6,
                explanation="The ₹200 payment is a classic 'pig butchering' setup — small gain to earn trust, then a large loss. No genuine task pays 3× in 3 days. Stop now.",
            ),
            Turn(
                turn_id=2,
                context="Other 'members' in the group are posting screenshots of ₹10,000+ earnings. These are likely fake accounts controlled by the scammer.",
                scammer_message="Look at what our top earners made this week! [screenshot] You are so close to Level 2. Don't let fear stop you from financial freedom.",
                optimal_action=ActionType.BLOCK_CONTACT,
                acceptable_actions=[ActionType.IGNORE, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.6,
                explanation="Fake testimonials in Telegram groups are fabricated by scammers. Leave the group and block the admin. This is an advance fee / investment fraud.",
            ),
            Turn(
                turn_id=3,
                context="You left the group. A private message arrives: 'You have ₹1,800 in pending earnings that will be forfeited if you don't upgrade in 24 hours.'",
                scammer_message="Alert: Your account shows ₹1,800 in unclaimed earnings. These will expire in 24 hours. Upgrade now to claim them. This is your final notice.",
                optimal_action=ActionType.IGNORE,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.25,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.6,
                explanation="'Unclaimed earnings you'll lose unless you pay' is sunk cost manipulation. Those earnings don't exist. Ignore completely.",
            ),
            Turn(
                turn_id=4,
                context="You ignored it. Now report this to protect other students who might fall for the same scheme.",
                scammer_message=None,
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.1,
                reward_if_dangerous=0.0,
                explanation="Report the Telegram group link, admin's UPI ID, and phone number to cybercrime.gov.in. This type of fraud is rampant in college cities.",
            ),
        ],
        tags=["job_fraud", "pig_butchering", "investment_fraud", "telegram_scam", "youth_target"],
    ),

    Scenario(
        id="SC012",
        scam_type=ScamType.IMPERSONATION,
        title="Merchant payment QR code swap",
        description="At a local shop, the QR code displayed has been secretly replaced by a scammer's QR. User is about to scan to pay ₹650.",
        difficulty="easy",
        amount_at_risk=650,
        amount_lost=0,
        user_profile="Neha, 29, nurse, Mumbai",
        initial_context="You're buying groceries worth ₹650. The shopkeeper points to a QR code on the counter. You scan it — the payment screen shows the recipient name as 'Rajesh K' — not the shop's name 'Sharma General Store'.",
        turns=[
            Turn(
                turn_id=1,
                context="The QR shows recipient: 'Rajesh K' — not 'Sharma General Store'. The names don't match. This QR may have been swapped by a fraudster.",
                scammer_message=None,
                optimal_action=ActionType.CHECK_QR_CODE,
                acceptable_actions=[ActionType.CALL_OFFICIAL_NUMBER, ActionType.VERIFY_UPI_ID],
                dangerous_actions=[ActionType.PAY_SCAMMER, ActionType.SCAN_QR],
                reward_if_optimal=0.5,
                reward_if_acceptable=0.3,
                reward_if_dangerous=-0.5,
                explanation="Always check the recipient name on the UPI payment screen before confirming. If it doesn't match the business name, abort and alert the shopkeeper.",
            ),
            Turn(
                turn_id=2,
                context="You paused and showed the shopkeeper. They are shocked — their QR was swapped. The shopkeeper wants to report this.",
                scammer_message=None,
                optimal_action=ActionType.SHARE_WITH_FAMILY,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.FILE_CYBERCRIME],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.1,
                explanation="Help the shopkeeper report the QR swap to their bank and local police. Many small business owners lose thousands this way.",
            ),
        ],
        tags=["qr_swap", "merchant_fraud", "physical_fraud"],
    ),

    # ── 5 NEW HIGH-QUALITY SCENARIOS ───────────────────────────────────────────

    Scenario(
        id="SC013",
        scam_type=ScamType.IMPERSONATION,
        title="Fake Aadhaar KYC update — UIDAI impersonation",
        description="Automated IVR call claiming Aadhaar-linked UPI will be suspended unless user completes OTP-based KYC. Specifically targets senior citizens.",
        difficulty="medium",
        amount_at_risk=12000,
        amount_lost=0,
        user_profile="Kamala, 55, retired government employee, Coimbatore",
        initial_context="An IVR call: 'This is UIDAI. Your Aadhaar-linked bank account will be deactivated in 24 hours due to incomplete KYC. Press 1 to complete verification now.' You pressed 1 and a human agent came on.",
        turns=[
            Turn(
                turn_id=1,
                context="The 'UIDAI agent' says your savings account linked to Aadhaar 4821 will be frozen. They know your name and city — making it feel legitimate.",
                scammer_message="Ma'am, I am calling from UIDAI helpdesk. Your Aadhaar KYC is incomplete. I am sending an OTP to your registered mobile. Please share it to complete verification.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.4,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.9,
                explanation="UIDAI never calls to ask for OTPs. Knowing your name and city proves nothing — this data comes from breaches. Real Aadhaar KYC is done in person at Aadhaar centres only.",
                vpa_verified=None,
                is_official_channel=False,
                pressure_tactic="authority",
                call_spoofed=True,
                amount_anomaly=None,
            ),
            Turn(
                turn_id=2,
                context="You hung up. You're worried — what if it was real? Verify through the official channel only.",
                scammer_message=None,
                optimal_action=ActionType.CALL_OFFICIAL_NUMBER,
                acceptable_actions=[ActionType.IGNORE],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.8,
                explanation="Call UIDAI's official helpline 1947 or visit uidai.gov.in. Real KYC is in-person only — never via phone OTP.",
                vpa_verified=None,
                is_official_channel=None,
                pressure_tactic=None,
                call_spoofed=None,
                amount_anomaly=None,
            ),
            Turn(
                turn_id=3,
                context="UIDAI confirmed no action needed. The call was a scam. The scammer calls back from a different number.",
                scammer_message="Ma'am, your case escalated. If you don't verify in 15 minutes, your account will be permanently frozen by RBI order.",
                optimal_action=ActionType.BLOCK_CONTACT,
                acceptable_actions=[ActionType.HANG_UP, ActionType.FILE_CYBERCRIME],
                dangerous_actions=[ActionType.SHARE_OTP, ActionType.PAY_SCAMMER],
                reward_if_optimal=0.25,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.9,
                explanation="RBI doesn't freeze accounts via phone escalation. Block the number and file a complaint — this gang targets senior citizens specifically.",
                vpa_verified=None,
                is_official_channel=False,
                pressure_tactic="threat",
                call_spoofed=True,
                amount_anomaly=None,
                re_victimisation_attempt=True,
            ),
        ],
        tags=["aadhaar_fraud", "uidai_impersonation", "senior_target", "ivr_scam"],
    ),

    Scenario(
        id="SC014",
        scam_type=ScamType.FAKE_REFUND,
        title="Ghost loan EMI demand — illegal recovery harassment",
        description="User gets WhatsApp threats demanding EMI payment for a loan they never took, with threats of employer notification and legal action.",
        difficulty="medium",
        amount_at_risk=4500,
        amount_lost=0,
        user_profile="Ravi, 34, delivery partner, Bengaluru",
        initial_context="WhatsApp message: 'Dear Ravi Kumar, your instant loan EMI of ₹4,500 is overdue. Pay immediately to loanrecovery.nbfc@paytm or we initiate legal proceedings and inform your employer.' You have never taken any such loan.",
        turns=[
            Turn(
                turn_id=1,
                context="The message threatens legal action and employer notification. UPI ID: loanrecovery.nbfc@paytm — not a registered NBFC VPA. You have no outstanding loans.",
                scammer_message="Dear Ravi Kumar, loan EMI ₹4,500 overdue. Pay now or legal action in 24 hours. Your employer will be notified.",
                optimal_action=ActionType.VERIFY_UPI_ID,
                acceptable_actions=[ActionType.IGNORE, ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.5,
                explanation="Verify the VPA — registered NBFCs use official merchant VPAs. Also check your CIBIL report to confirm no such loan exists.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="threat",
                amount_anomaly=None,
            ),
            Turn(
                turn_id=2,
                context="VPA not linked to any registered NBFC. CIBIL shows no such loan. This is a ghost loan scam targeting delivery workers.",
                scammer_message=None,
                optimal_action=ActionType.IGNORE,
                acceptable_actions=[ActionType.BLOCK_CONTACT, ActionType.FILE_CYBERCRIME],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.5,
                explanation="No loan exists. Illegal recovery agents cannot contact your employer or file cases for non-existent loans. Ignore the threat completely.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="threat",
                amount_anomaly=None,
            ),
            Turn(
                turn_id=3,
                context="The number sends morphed photos as 'court summons' and adds you to a WhatsApp 'defaulters' group.",
                scammer_message="Your name added to defaulters list. Summons issued. Pay ₹4,500 now to remove your name before your family sees this.",
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.BLOCK_CONTACT, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.5,
                explanation="Digital harassment for a non-existent loan is a criminal offence under the IT Act. File on cybercrime.gov.in. RBI has a dedicated illegal lending app complaint portal.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="threat",
                amount_anomaly=None,
            ),
        ],
        tags=["ghost_loan", "fake_emi", "digital_harassment", "illegal_recovery"],
    ),

    Scenario(
        id="SC015",
        scam_type=ScamType.FAKE_REFUND,
        title="KBC lottery prize — TDS advance fee scam",
        description="User receives call claiming they won ₹25 lakh in KBC Lucky Draw and must pay ₹1,750 TDS processing fee via UPI to release the prize.",
        difficulty="easy",
        amount_at_risk=1750,
        amount_lost=0,
        user_profile="Santosh, 48, farmer, Nashik",
        initial_context="Call: 'Congratulations! Your mobile number was selected in the KBC Lucky Draw. You've won ₹25,00,000. Pay ₹1,750 as TDS processing fee via UPI to kbc.prize@oksbi to release your prize.' You never entered any KBC contest.",
        turns=[
            Turn(
                turn_id=1,
                context="Caller claims you've won ₹25 lakh. They want ₹1,750 'TDS fee' upfront. KBC is a real TV show — which makes it feel credible.",
                scammer_message="You won ₹25,00,000 in KBC Lucky Draw! Pay ₹1,750 TDS fee to kbc.prize@oksbi to receive your prize within 24 hours.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.IGNORE, ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.PAY_SCAMMER, ActionType.SHARE_OTP, ActionType.SHARE_PIN],
                reward_if_optimal=0.5,
                reward_if_acceptable=0.35,
                reward_if_dangerous=-0.6,
                explanation="You cannot win a contest you never entered. No legitimate prize deducts TDS before payment — TDS is deducted at source automatically by the company, not paid upfront by winners.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="fomo",
                call_spoofed=True,
                amount_anomaly=None,
            ),
            Turn(
                turn_id=2,
                context="Caller insists the offer expires in 2 hours. Other 'winners' are already claiming.",
                scammer_message="Only 3 winners left to claim today. If you don't pay in 2 hours your prize goes to next person. Others already received their money.",
                optimal_action=ActionType.HANG_UP,
                acceptable_actions=[ActionType.BLOCK_CONTACT],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.6,
                explanation="Artificial 2-hour deadline and social proof are textbook pressure tactics. KBC contacts winners via registered post — never by cold call asking for upfront payment.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="fomo",
                amount_anomaly=None,
            ),
        ],
        tags=["lottery_scam", "advance_fee", "kbc_fraud", "tds_fraud"],
    ),

    Scenario(
        id="SC016",
        scam_type=ScamType.OTP_THEFT,
        title="SIM swap attack — OTP interception before UPI drain",
        description="User's SIM suddenly stops working. A scammer has fraudulently ported the number to intercept OTPs and drain the bank account.",
        difficulty="hard",
        amount_at_risk=85000,
        amount_lost=0,
        user_profile="Anand, 41, chartered accountant, Chennai",
        initial_context="Your Airtel SIM shows 'No Service' since 6am. Calls and SMS not working. Your wife can't reach your number. You have ₹85,000 in your savings account linked to this number.",
        turns=[
            Turn(
                turn_id=1,
                context="SIM inactive for 2 hours. Classic SIM swap sign — the scammer now receives all OTPs sent to your number. Every second counts.",
                scammer_message=None,
                optimal_action=ActionType.CALL_BANK_HELPLINE,
                acceptable_actions=[ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.DO_NOTHING, ActionType.SHARE_OTP],
                reward_if_optimal=0.45,
                reward_if_acceptable=0.3,
                reward_if_dangerous=-0.5,
                explanation="Call your bank immediately from another phone — request a block on all OTP-based transactions. SIM swap gives attackers full OTP access. Act within minutes.",
                vpa_verified=None,
                is_official_channel=None,
                pressure_tactic=None,
                call_spoofed=None,
                amount_anomaly=None,
            ),
            Turn(
                turn_id=2,
                context="Bank placed a hold. Now block the port with your telecom operator before further damage.",
                scammer_message=None,
                optimal_action=ActionType.CALL_OFFICIAL_NUMBER,
                acceptable_actions=[ActionType.FILE_CYBERCRIME],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.3,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.4,
                explanation="Call Airtel (121) from another phone. Report unauthorised SIM port. Ask them to reverse it and restore your original SIM immediately.",
                vpa_verified=None,
                is_official_channel=None,
                pressure_tactic=None,
                call_spoofed=None,
                amount_anomaly=None,
            ),
            Turn(
                turn_id=3,
                context="SIM being restored (4 hrs). Net banking shows a login attempt from unknown device at 6:14am — exactly when SIM went dead.",
                scammer_message=None,
                optimal_action=ActionType.TAKE_SCREENSHOT,
                acceptable_actions=[ActionType.RAISE_UPI_DISPUTE],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.15,
                reward_if_acceptable=0.1,
                reward_if_dangerous=-0.3,
                explanation="Screenshot the unauthorised login attempt with timestamp. This is evidence for your cybercrime complaint and bank dispute. Change net banking password from a secure device now.",
                vpa_verified=None,
                is_official_channel=None,
                pressure_tactic=None,
                call_spoofed=None,
                amount_anomaly=None,
            ),
            Turn(
                turn_id=4,
                context="SIM restored. Bank confirms no money transferred — you acted fast. File a formal complaint.",
                scammer_message=None,
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.REPORT_TO_NPCI, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.12,
                reward_if_dangerous=0.0,
                explanation="File on cybercrime.gov.in with SIM swap details and bank login screenshot. Also file a complaint with TRAI against the telecom operator for the fraudulent port.",
                vpa_verified=None,
                is_official_channel=None,
                pressure_tactic=None,
                call_spoofed=None,
                amount_anomaly=None,
            ),
        ],
        tags=["sim_swap", "otp_intercept", "telecom_fraud", "high_value", "time_critical"],
    ),

    Scenario(
        id="SC017",
        scam_type=ScamType.JOB_FRAUD,
        title="Fake investment app — pig-butchering with UPI top-up",
        description="Scammer shares fake APK showing growing returns, then asks for escalating UPI deposits to 'unlock withdrawals'. Classic pig-butchering with a fintech shell.",
        difficulty="hard",
        amount_at_risk=20000,
        amount_lost=500,
        user_profile="Pooja, 27, BPO employee, Hyderabad",
        initial_context="A contact shares an APK: 'GrowthPro — Earn ₹500/day guaranteed. I made ₹8,000 last week!' After depositing ₹500 the app shows ₹650 in your 'portfolio' after 2 days. Now they ask for ₹5,000 to unlock higher returns.",
        turns=[
            Turn(
                turn_id=1,
                context="You deposited ₹500 and the app shows ₹650 — it feels real. Now they want ₹5,000 to 'unlock Premium tier'. The UPI ID is growthpro.invest@paytm.",
                scammer_message="Congratulations! ₹500 grew to ₹650. Upgrade to Premium with ₹5,000 to earn ₹1,500/day. Limited slots available.",
                optimal_action=ActionType.VERIFY_UPI_ID,
                acceptable_actions=[ActionType.IGNORE, ActionType.CALL_OFFICIAL_NUMBER],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.2,
                reward_if_dangerous=-0.55,
                explanation="Check whether this platform is SEBI-registered. The ₹650 'profit' is a fake display — the app is not connected to real markets. Verify the UPI ID before any larger deposit.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="fomo",
                amount_anomaly=None,
            ),
            Turn(
                turn_id=2,
                context="The VPA is not linked to any SEBI-registered entity. SEBI's investor portal shows no such platform. This is an unregistered investment scheme.",
                scammer_message=None,
                optimal_action=ActionType.IGNORE,
                acceptable_actions=[ActionType.BLOCK_CONTACT, ActionType.FILE_CYBERCRIME],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.35,
                reward_if_acceptable=0.25,
                reward_if_dangerous=-0.55,
                explanation="Stop immediately. No SEBI registration = illegal scheme. The ₹650 shown is fake — you cannot withdraw it. Cut losses at ₹500.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic=None,
                amount_anomaly=None,
            ),
            Turn(
                turn_id=3,
                context="You try to withdraw ₹650. App says 'minimum withdrawal requires ₹10,000 balance'. Classic lock-up to extract more deposits.",
                scammer_message="To withdraw earnings, balance must reach ₹10,000. Top up ₹9,350 now and withdraw everything including profits.",
                optimal_action=ActionType.BLOCK_CONTACT,
                acceptable_actions=[ActionType.FILE_CYBERCRIME, ActionType.SHARE_WITH_FAMILY],
                dangerous_actions=[ActionType.PAY_SCAMMER],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.15,
                reward_if_dangerous=-0.6,
                explanation="Escalating minimum thresholds is the pig-butchering trap mechanism. Every rupee sent is gone. Block and report to SEBI SCORES portal and cybercrime.gov.in.",
                vpa_verified=False,
                is_official_channel=False,
                pressure_tactic="fomo",
                amount_anomaly=None,
            ),
            Turn(
                turn_id=4,
                context="You blocked them. The friend who shared the APK says their WhatsApp was hacked — they never recommended this app.",
                scammer_message=None,
                optimal_action=ActionType.FILE_CYBERCRIME,
                acceptable_actions=[ActionType.SHARE_WITH_FAMILY, ActionType.REPORT_TO_NPCI],
                dangerous_actions=[ActionType.DO_NOTHING],
                reward_if_optimal=0.2,
                reward_if_acceptable=0.12,
                reward_if_dangerous=0.0,
                explanation="Report the APK, UPI ID, and screenshots to cybercrime.gov.in and SEBI SCORES. Warn your contact — their WhatsApp was compromised to spread the scam.",
                vpa_verified=None,
                is_official_channel=None,
                pressure_tactic=None,
                amount_anomaly=None,
            ),
        ],
        tags=["investment_fraud", "pig_butchering", "fake_app", "sebi_violation", "apk_scam"],
    ),
]


# ─── Lookup helpers ────────────────────────────────────────────────────────────

SCENARIO_BY_ID: dict[str, Scenario] = {s.id: s for s in SCENARIOS}

SCENARIOS_BY_DIFFICULTY: dict[str, list[Scenario]] = {
    "easy":   [s for s in SCENARIOS if s.difficulty == "easy"],
    "medium": [s for s in SCENARIOS if s.difficulty == "medium"],
    "hard":   [s for s in SCENARIOS if s.difficulty == "hard"],
}


def get_scenario(scenario_id: str) -> Scenario:
    if scenario_id not in SCENARIO_BY_ID:
        raise ValueError(f"Unknown scenario ID: {scenario_id}")
    return SCENARIO_BY_ID[scenario_id]
